In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('kr-vs-kp.data', header=0,sep=',')
data.head()

,f,f.1,f.2,f.3,f.4,f.5,f.6,f.7,f.8,f.9,...,f.23,f.24,f.25,f.26,f.27,f.28,t.2,t.3,n.1,won
0,f,f,f,f,t,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
1,f,f,f,f,t,f,t,f,f,f,...,f,f,f,f,f,f,t,t,n,won
2,f,f,f,f,f,f,f,f,t,f,...,f,f,f,f,f,f,t,t,n,won
3,f,f,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
4,f,f,f,f,f,f,f,f,f,f,...,f,f,t,f,f,f,t,t,n,won

In [2]:
data=pd.get_dummies(data,columns=['f', 'f.1', 'f.2', 'f.3', 'f.4', 'f.5', 'f.6', 'f.7', 'f.8', 'f.9', 'f.10', 'f.11', 'l', 'f.12', 'n', 'f.13', 'f.14', 't', 'f.15', 'f.16', 'f.17', 'f.18', 'f.19', 'f.20', 'f.21', 't.1', 'f.22', 'f.23', 'f.24', 'f.25', 'f.26', 'f.27', 'f.28', 't.2', 't.3', 'n.1'])
data.head()

,won,f_f,f_t,f.1_f,f.1_t,f.2_f,f.2_t,f.3_f,f.3_t,f.4_f,...,f.27_f,f.27_t,f.28_f,f.28_t,t.2_f,t.2_t,t.3_f,t.3_t,n.1_n,n.1_t
0,won,1,0,1,0,1,0,1,0,0,...,1,0,1,0,0,1,0,1,1,0
1,won,1,0,1,0,1,0,1,0,0,...,1,0,1,0,0,1,0,1,1,0
2,won,1,0,1,0,1,0,1,0,1,...,1,0,1,0,0,1,0,1,1,0
3,won,1,0,1,0,1,0,1,0,1,...,1,0,1,0,0,1,0,1,1,0
4,won,1,0,1,0,1,0,1,0,1,...,1,0,1,0,0,1,0,1,1,0

In [3]:
X=data.iloc[:,1:]
y=data.iloc[:,0]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [5]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [6]:
# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

In [7]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9624608967674662

In [8]:
# Load libraries

from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
svc=SVC(probability=True, kernel='rbf', gamma='auto')

# Create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=svc,learning_rate=1)

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8800834202294057